export { DetalleCompraService } from './componentes/detalleCompra.service';
export { MarcaService } from './componentes/marca.service';
export { ModeloService } from './componentes/modelo.service';
export { OrdenCompraService } from './componentes/ordenCompra.service';
export { PersonaService } from './componentes/persona.service';
export { ProveedorService } from './componentes/proveedor.service';
export { TipoEquipamientoService } from './componentes/tipoEquipamiento.service';
export { UsuarioService } from './componentes/usuario.service';
export { UserxsService } from './componentes/userxs.service';
export { EstadoEquipoService } from './componentes/estado-equipo.service';
export { EquipoService } from './componentes/equipo.service'